### ISSUE TITLE
Wrong netmask when configuring interface address through CLI

### ISSUE THREAD

**Issue by semihalf-berestovskyy-andriy** [OpenFastPath/ofp#101]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 101
Date: 2016-10-13 14:11:18 +0200
From: janne.peltonen@nokia.com
To:   Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;
CC:   sorin.vultureanu@enea.com

Last updated: 2016-11-28 15:31:27 +0100

## Bugzilla Comment ID: 189
Date: 2016-10-13 14:11:18 +0200
From: janne.peltonen@nokia.com

When an interface address and subnet is configured through the CLI,
the fast path tries to sync the configuration to the OS kernel
with an incorrect netmask.

For example, ifconfig fp0 10.0.0.1/24 command in CLI results in
fast path invoking ifconfig fp0 11.0.0.1 netmask 0.255.255.255 up

Since the netmask is invalid, my system seems to fall back to
mask lenght of 8 bits so that in kernel the interface gets the
address 11.0.0.1/8. The incorrect subnet in kernel config
gets then synced back to fast path through a netlink notification
so that also the fast path ends up having an incorrect netmask.

The bug is caused by ofp_config_interface_up_v4() keeping
netmask in a local variable in the big endian byte order but
failing to convert it back to the native byte order before
calculating the arguments for ifconfig.

OFP version: 2.0.0

## Bugzilla Comment ID: 212
Date: 2016-11-28 15:31:27 +0100
From: Jere Leppänen &lt;<jere.leppanen@nokia.com>&gt;

*** Bug #105 has been marked as a duplicate of this bug. ***

**Comment by JereLeppanen** [comment]
Fixed in commit 86914106a77d29c99bf52efff550f44d7708d53d.
