### ISSUE TITLE
The number of pktin queues in NGiNX should be dynamically assigned

### ISSUE THREAD

**Issue by semihalf-berestovskyy-andriy** [OpenFastPath/ofp#108]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 108
Date: 2016-10-20 09:03:43 +0200
From: Josep Puigdemont &lt;<josep.puigdemont@linaro.org>&gt;
To:   openfastpath@list.openfastpath.org

Last updated: 2016-10-20 09:03:43 +0200

## Bugzilla Comment ID: 196
Date: 2016-10-20 09:03:43 +0200
From: Josep Puigdemont &lt;<josep.puigdemont@linaro.org>&gt;

The number of pktin queues used by NGiNX is currently set at compile time, making the server restricted to use only one worker with the current defaults. This option should instead be configured dynamically at run-time, and it should honor the worker_processes option in the nginx.conf configuration file.

**Comment by sovu** [comment]
commit 152cfb0c105306432eb601967a3f4bd760507a58
Author: Jere Leppänen <jere.leppanen@nokia.com>
Date:   Mon Mar 6 23:34:51 2017 +0200

    Make NUM_QUEUES an environment variable instead of a preprocessor define.

    Signed-off-by: Jere Leppänen <jere.leppanen@nokia.com>
