### ISSUE TITLE
OFP performance measurement procedure Mpps also be 0.000

### ISSUE THREAD

**Issue by semihalf-berestovskyy-andriy** [OpenFastPath/ofp#109]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 109
Date: 2016-10-21 07:27:52 +0200
From: xiaowen yang &lt;<xiaowen.1.yang@gmail.com>&gt;
To:   openfastpath@list.openfastpath.org
CC:   xiaowen.1.yang@gmail.com

Last updated: 2016-10-21 11:04:06 +0200

## Bugzilla Comment ID: 197
Date: 2016-10-21 07:27:52 +0200
From: xiaowen yang &lt;<xiaowen.1.yang@gmail.com>&gt;

Created attachment 10
test result

I used free SW tool iperf to generate data. But it is odd.
Below is the testing data.
Bandwidth is 1.42 Gbits/Sec without OFP
Bandwidth is 974Mbits/Sec with OFP.
 
and node2 show Mpps aslo 0.
 
Why does the performance drop with OFP ? 
Node3 : 192.168.30.3
Node2: 192.168.30.1 and 192.168.10.1 OFP and ODP with platform linux-generic (no DPDK) on Node2
Node1:192.168.10.3

case steps:
1.       Start application that uses OFP on node 2. Ex:

./fpm -i interface0,interface1 -c 3 -p

2.       Connect with telnet to OFP CLI on port 2345. To connect remotely you need to have a management interface/IP on node 2.

telnet 127.0.0.1 2345

3.       Configure IPs on fpX interfaces with commands:

ifconfig fp0 192.168.10.1/24

ifconfig fp1 192.168.30.1/24

4.       Ping node 2 from node 3 in order to populate the ARP table. Doing this prior to the high load test start avoids the loss of ARP responses due to depleted packet buffers. I.e. before they can be handled by the normal ARP request / ARP response procedure.

5.       Generate traffic from packet generator (node 1)

6.       Collect results from destination (node 3) or from OFP application (node 2).

testing reslut link as below:

https://mail.google.com/mail/?ui=2&ik=625a950c90&view=fimg&th=157e25ef18698fbc&attid=0.1&disp=emb&attbid=ANGjdJ91ho0HOQcDry-m4LpONrvemYh-NifQsi-lUfUBNbhCT8cRO0SHAHW9IkG_mQpH3lSGpaNmf-7kn-4cZMcC3J90GRJi6uFYAW7Io9vBcfKtUVcOb6peFO5zySs&sz=w1524-h858&ats=1477026903255&rm=157e25ef18698fbc&zw&atsh=1

https://mail.google.com/mail/?ui=2&ik=625a950c90&view=fimg&th=157e25ef18698fbc&attid=0.2&disp=emb&attbid=ANGjdJ8kSa4dgZn9jrf36jThARmFr265q_muZu7CK_asCkFwqT7nnZfB9PU6GGa6A1oPcg-etg-0WXgQx5-aRLGLYuTCZXVS4hFU3pReB-i-FHlPK-aa0ldTY-4EJnw&sz=w1420-h966&ats=1477026903255&rm=157e25ef18698fbc&zw&atsh=1

> Attached file: OFP1.png (image/png, 67206 bytes)
> Description:   test result

**Comment by ViktorTikkanen** [comment]
Hi!

Is this issue still actual? If so, please send test results and attachments again since old links don't work anymore.

**Comment by sovu** [comment]
1 year old post.
