### ISSUE TITLE
odp build issues

### ISSUE THREAD

**Issue by rlee3030** [OpenFastPath/ofp#13]
After cloning odp and tried to run ./bootstrap but ran into errors below.
I am running on Centos 6 linux.
## Any help will be appreciated.  Thx.

[root@localhost odp]# ./bootstrap
- aclocal -I config -I m4
  configure.ac:28: warning: macro `AM_PROG_AR' not found in library
- libtoolize --copy
  libtoolize: putting auxiliary files in `.'.
  libtoolize: copying file`./ltmain.sh'
  libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
  libtoolize: copying file`m4/libtool.m4'
  libtoolize: copying file `m4/ltoptions.m4'
  libtoolize: copying file`m4/ltsugar.m4'
  libtoolize: copying file `m4/ltversion.m4'
  libtoolize: copying file`m4/lt~obsolete.m4'
- autoheader
- automake --add-missing --copy --warnings=all
  configure.ac:23: installing `./compile'
  configure.ac:32: installing`./config.guess'
  configure.ac:32: installing `./config.sub'
  configure.ac:3: installing`./install-sh'
  configure.ac:3: installing `./missing'
  example/classifier/Makefile.am: installing`./depcomp'
- autoconf --force
  configure.ac:30: error: possibly undefined macro: AM_PROG_AR
    If this token and others are legitimate, please use m4_pattern_allow.
    See the Autoconf documentation.
  configure:44072: error: possibly undefined macro: m4_argn
  configure:44072: error: possibly undefined macro: m4_default_nblank_quoted

**Comment by sovu** [comment]
Can you try adding in configure.ac the following line ?
m4_pattern_allow([AM_PROG_AR])

**Comment by semihalf-berestovskyy-andriy** [comment]
Note: the comment was created automatically with bugzilla2github tool

---
**Bugzilla bug ID:  13**
**Renumbered to issue: #136**

**Comment by sovu** [comment]
No response.
Anyway, we don't support CentOS 6.
