### ISSUE TITLE
OFP Build fatal Error shared_memory.h Not Found

### ISSUE THREAD

**Issue by ihalloum** [OpenFastPath/ofp#148]
OS: Ubuntu Server 16.04.2 amd64  running on VMware Workstation 12 Pro
#
I download ODP and Build it like this:
```
git clone https://github.com/OpenFastPath/ofp
./bootstrap
./configure --prefix=/usr/local/odp/
make
make install
```
![odpls](https://cloud.githubusercontent.com/assets/10779546/23259512/22695f34-f9d6-11e6-9850-a0f808bbad25.JPG)

After that I downloaded OFP and try to build it:
```
git clone https://github.com/OpenFastPath/ofp
./bootstrap
```
![ofpboot](https://cloud.githubusercontent.com/assets/10779546/23259513/227166e8-f9d6-11e6-95f1-e63c3bc5a749.JPG)
`./configure --prefix=/usr/local/ofp/ --with-odp=/usr/local/odp/ --enable-cunit
`![ofpconfig](https://cloud.githubusercontent.com/assets/10779546/23259514/2274d364-f9d6-11e6-8a58-0da08b6995a6.JPG)
`make
`![ofpmake](https://cloud.githubusercontent.com/assets/10779546/23259515/227c650c-f9d6-11e6-964e-973ddf12eae3.JPG)

I faced this error 

> Making all in scripts
> make[1]: Entering directory '/work/ofp/scripts'
> make[1]: Nothing to be done for 'all'.
> make[1]: Leaving directory '/work/ofp/scripts'
> Making all in src
> make[1]: Entering directory '/work/ofp/src'
>   CC       ofp_pkt_processing.lo
> In file included from /usr/local/odp//include/odp/api/barrier.h:22:0,
>                  from /usr/local/odp//include/odp_api.h:31,
>                  from /usr/local/odp//include/odp.h:21,
>                  from ../include/ofpi.h:11,
>                  from ofp_pkt_processing.c:35:
> /usr/local/odp//include/odp/api/plat/shared_memory_types.h:23:39: fatal error: odp/api/abi/shared_memory.h: No such file or directory
> compilation terminated.
> Makefile:646: recipe for target 'ofp_pkt_processing.lo' failed
> make[1]: *** [ofp_pkt_processing.lo] Error 1
> make[1]: Leaving directory '/work/ofp/src'
> Makefile:587: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1
>

**Comment by bogdanPricope** [comment]
Hi,

OFP (master branch) supports only one ODP version: monarch_lts

On odp, try:
git checkout -b test_monarch_lts origin/monarch_lts

BR,
Bogdan

**Comment by ihalloum** [comment]
thank you :) the problem was solved :) :)

I want to write network app like TCP Echo using OFP lib
Do you have any doc for this ?? 

thanks
