### ISSUE TITLE
Does OFP not support tcp retransmission timer?

### ISSUE THREAD

**Issue by muziding** [OpenFastPath/ofp#15]
`callout_pending` is always true in `ofp_tcp_timer_rexmt`, 
so  `ofp_tcp_timer_rexmt` always returns after calling `callout_pending`.
# vi ofp_tcp_timer.c

420  ofp_tcp_timer_rexmt(void \* xtp)
.......
446     if ((inp->inp_flags & INP_DROPPED) || callout_pending(&tp->t_timers->tt_rexmt)
447         || !callout_active(&tp->t_timers->tt_rexmt)) {
448         INP_WUNLOCK(inp);
449         INP_INFO_RUNLOCK(&V_tcbinfo);
450         return;
451     }
......

**Comment by semihalf-berestovskyy-andriy** [comment]
Note: the comment was created automatically with bugzilla2github tool

---
**Bugzilla bug ID:  15**
**Renumbered to issue: #138**

**Comment by sovu** [comment]
commit 82566800f1cc31ffdf2c96aa6dd25ba213a69aca
Author: Sorin.Vultureanu <Sorin.Vultureanu@enea.com>
Date:   Mon Dec 5 16:04:42 2016 +0200

    tcp: Fix callout_pending value

    The hardcoded value of 1 returned for callout_pending() cause the handlers
    to always return without doing anything. The CALLOUT_PENDING flag is never
    set on callout_pending() so the hardcoded return value should be 0.

    Fixes: #98 TCP timers problems

    Patch-by: Jason Preston <jpreston@infinite.io>
    Signed-off-by: Sorin Vultureanu <Sorin.Vultureanu@enea.com>
    Reviewed-by: Jere Leppänen <jere.leppanen@nokia.com>
