### ISSUE TITLE
error when make ofp

### ISSUE THREAD

**Issue by billyxue** [OpenFastPath/ofp#151]
help

evn:  vmware  
centos 7.2

odp
git from github 
make install ok
dir: /usr/local/odp

--------------
ofp 
git from github

[root@localhost ofp]# make
Making all in scripts
make[1]: Entering directory `/root/ofp/scripts'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/root/ofp/scripts'
Making all in src
make[1]: Entering directory `/root/ofp/src'
  CC       ofp_pkt_processing.lo
In file included from ofp_pkt_processing.c:35:0:
../include/ofpi.h:12:30: fatal error: odp/helper/linux.h: No such file or directory
 #include <odp/helper/linux.h>
                              ^
compilation terminated.
make[1]: *** [ofp_pkt_processing.lo] Error 1
make[1]: Leaving directory `/root/ofp/src'
make: *** [all-recursive] Error 1

and I can not find the file match the name linux.h

find /usr/local/odp/ |grep linux.h 
[empty]

thanks

**Comment by bogdanPricope** [comment]
git clone https://git.linaro.org/lng/odp.git
cd odp
git checkout -b monarch_build origin/monarch_lts

**Comment by ViktorTikkanen** [comment]
Hi Billy!

Can this issue be closed now?
