### ISSUE TITLE
unknown type name 'fd_set'

### ISSUE THREAD

**Issue by w675881684** [OpenFastPath/ofp#153]
unknown type name 'fd_set'

![default](https://cloud.githubusercontent.com/assets/11437110/25609697/d925a53c-2f52-11e7-8331-18d37b1d7c2b.png)

**Comment by JereLeppanen** [comment]
Which distro and distro version are you compiling on?

Try this patch: http://www.openfastpath.org/pipermail/openfastpath/2017-May/001921.html

**Comment by w675881684** [comment]
RHEL7.2

**Comment by JereLeppanen** [comment]
Okay, in that case the patch should fix it.

**Comment by w675881684** [comment]
thanks a lot!
update gblic to 2.20 solve this problem.


by the way: may be need to update libnl3-devel
grep -r nla_nest_cancel /usr/include/libnl3/
无nla_nest_cancel函数

[@l_177_52 /opt/ofp]# rpm -qf /usr/include/libnl3/netlink/attr.h
libnl3-devel-3.2.21-10.el7.x86_64
[@l_177_52 /opt/ofp]# rpm -qa|grep libnl
libnl3-3.2.21-10.el7.x86_64
libnl3-cli-3.2.21-10.el7.x86_64
libnl-1.1.4-3.el7.x86_64
libnl3-devel-3.2.21-10.el7.x86_64

libnl3-cli-3.2.28-3.el7_3.x86_64
wget ftp://195.220.108.108/linux/centos/7.3.1611/updates/x86_64/Packages/libnl3-cli-3.2.28-3.el7_3.x86_64.rpm
wget ftp://195.220.108.108/linux/centos/7.3.1611/updates/x86_64/Packages/libnl3-3.2.28-3.el7_3.x86_64.rpm
wget ftp://195.220.108.108/linux/centos/7.3.1611/updates/x86_64/Packages/libnl3-devel-3.2.28-3.el7_3.x86_64.rpm
rpm -Uvh libnl3-*
rpm -ivh libnl3-devel-3.2.28-3.el7_3.x86_64.rpm
grep -r nla_nest_cancel /usr/include/libnl3/
/usr/include/libnl3/netlink/attr.h:extern void nla_nest_cancel(struct nl_msg *, const struct nlattr *);


https://github.com/lvsgate/lvs-dpdk/issues/2

**Comment by JereLeppanen** [comment]
> update gblic to 2.20 solve this problem.

Yes, that'll work too,

> by the way: may be need to update libnl3-devel
> grep -r nla_nest_cancel /usr/include/libnl3/

ofp doesn't use nla_nest_cancel, but your application may be. Nothing to do with ofp, I think.
