### ISSUE TITLE
Misleading configuration instruction in readme (odp-dpdk).

### ISSUE THREAD

**Issue by semihalf-szymon** [OpenFastPath/ofp#155]
In the repository main Readme there is a note to add some flags
when configuring for odp-dpdk, namely:
`    (if using DPDK)
  --enable-shared=no
  --enable-sp=no`
I found this information very misleading as I also needed at least 
the flag
`--with-odp-lib=odp-dpdk`
I guess that it is necessary to compile for odp-dpdk, isn't it?
(please correct me if I am wrong)
I am not sure where it is the right place to put the configuration
instructions, but if it is done so I reckon it should be at least
minimally complete.

**Comment by sovu** [comment]
To build with an odp library different than odp-linux, for example odp-dpdk you need to specify this with --with-odp-lib configure parameter.

On the latest master only "--with-odp-lib=odp-dpdk" is mandatory, while these "--enable-shared=no" or "--enable-sp=no" are not necessary.

**Comment by ViktorTikkanen** [comment]
Hi!

Can this issue be closed now?

What comes to building with ODP-DPDK, README refers now to the OFP User guide.
