### ISSUE TITLE
Support for Wireless NICs

### ISSUE THREAD

**Issue by arun1993** [OpenFastPath/ofp#159]
I believe wireless NICs would be able to handle higher amount of data in future and bringing in support of OFP for wireless NICs earlier would be beneficial. Linux has the mac80211 framework helping 802.11 driver developers. I would like to work on this; Any suggestions regarding this would be welcome.

**Comment by sovu** [comment]
Hi,

Agreed, but I think "mac80211 framework helping 802.11 driver developers" is better suited for opendataplane project.
See:
https://www.opendataplane.org/

BR,
Sorin
