### ISSUE TITLE
nginx proxy mode problem

### ISSUE THREAD

**Issue by yulintao** [OpenFastPath/ofp#16]
hi,
I used nginx_ofp for proxy mode ,but it doesn't work.
I find that nginx_ofp and upstream has not establishment .(upstream response "syn+ack" but ofp didn't process it),I don't no why ,please help me,thanks

**Comment by semihalf-berestovskyy-andriy** [comment]
Note: the comment was created automatically with bugzilla2github tool

---
**Bugzilla bug ID:  16**
**Renumbered to issue: #139**

**Comment by jlijian3** [comment]
May be the core processed  syn+ack  was not the core send syn packet, it can not find the connection in different core.
