### ISSUE TITLE
sudo ./scripts/start_device.sh eth0

### ISSUE THREAD

**Issue by shixiongzzz** [OpenFastPath/ofp#17]
sysctl: cannot stat /proc/sys/net/ipv6/conf/fp0/autoconf: 没有那个文件或目录
Internet Systems Consortium DHCP Client 4.2.4
Copyright 2004-2012 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Cannot find device "fp0"
Error getting hardware address for "fp0": No such device

**Comment by semihalf-berestovskyy-andriy** [comment]
Note: the comment was created automatically with bugzilla2github tool

---
**Bugzilla bug ID:  17**
**Renumbered to issue: #140**

**Comment by sovu** [comment]
Configuration issue. 
Probably interface name is invalid or used for an unsupported usecase.
Maybe we should better clarify what should be the interface name for what usecase; i.e. 0,1 for DPDK, eth0 when SP is enabled.
