### ISSUE TITLE
Receive DUP! packets when ping

### ISSUE THREAD

**Issue by dosarudaniel** [OpenFastPath/ofp#174]
In order to measure OpenFastPath Performance using this [procedure](https://github.com/OpenFastPath/ofp/wiki/OpenFastPath-Performance-Measurement-Procedure) I used this setup: 
I have 3 vms on VMWare Player with ubuntu 16.04 which form this topology: 
![image](https://user-images.githubusercontent.com/15221288/28610767-2d57a3c6-71f2-11e7-9c30-544f3a60e3e2.png)
For node 2 I followed these [steps](https://git.linaro.org/lng/odp-dpdk.git/tree/platform/linux-dpdk/READM) (mostly step 4 since I had odp-dpdk compiled). 

I have two interfaces controlled by DPDK as I show here:
daniel@ubuntu:~/ofp/scripts/dpdk$ ./tools/dpdk-devbind.py --status
Network devices using DPDK-compatible driver
0000:02:01.0 '82545EM Gigabit Ethernet Controller (Copper)' drv=igb_uio unused=e1000
0000:02:06.0 '82545EM Gigabit Ethernet Controller (Copper)' drv=igb_uio unused=e1000

When I ping  fp0 interface from node 1 or node 3 from node 1 I receive duplicated packets:
**[ping node 1 -> fp0]**
daniel@ubuntu:~$ ping 192.168.10.2
PING 192.168.10.2 (192.168.10.2) 56(84) bytes of data.
64 bytes from 192.168.10.2: icmp_seq=1 ttl=64 time=0.247 ms
64 bytes from 192.168.10.2: icmp_seq=1 ttl=64 time=0.581 ms (DUP!)
64 bytes from 192.168.10.2: icmp_seq=1 ttl=63 time=0.590 ms (DUP!)
[...]
64 bytes from 192.168.10.2: icmp_seq=1 ttl=1 time=1.83 ms (DUP!)
64 bytes from 192.168.10.2: icmp_seq=1 ttl=1 time=1.83 ms (DUP!)
^C
--- 192.168.10.2 ping statistics ---
1 packets transmitted, 1 received, +127 duplicates, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.247/1.147/1.838/0.418 ms

**[ping node 1 -> node3]**
daniel@ubuntu:~$ ping 192.168.20.1
PING 192.168.20.1 (192.168.20.1) 56(84) bytes of data.
64 bytes from 192.168.20.1: icmp_seq=1 ttl=63 time=0.265 ms
From 192.168.10.2 icmp_seq=1 Time to live exceeded
64 bytes from 192.168.20.1: icmp_seq=1 ttl=63 time=0.284 ms (DUP!)
64 bytes from 192.168.20.1: icmp_seq=1 ttl=63 time=0.286 ms (DUP!)
[...]
64 bytes from 192.168.20.1: icmp_seq=1 ttl=5 time=135 ms (DUP!)
64 bytes from 192.168.20.1: icmp_seq=1 ttl=5 time=135 ms (DUP!)
^C
--- 192.168.20.1 ping statistics ---
1 packets transmitted, 1 received, +7301 duplicates, +52 errors, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.265/91.998/135.504/32.493 ms

Performance measure is **not** correct since fpm shows:
[...]
Mpps:0.056
Mpps:0.056
[...]

For me it seems like an OFP issue related to the way icmp request/reply is handled. It might need further investigation enabling packet debug traces..

How can I solve this?

**Comment by ViktorTikkanen** [comment]
Hi!

It looks like both OFP and Linux stack are responding to the ICMP requests. Have you tried to compile OFP using "--enable-sp=no" (= "--disable-sp") configuration option?
