### ISSUE TITLE
Cannot make OpenFastPath

### ISSUE THREAD

**Issue by Pavel-Melnikov** [OpenFastPath/ofp#175]
Hello, I am having an issue with building ofp
after setting ./configure --prefix="/home/pmelnikov/odp/odp/odp"
and  running make I get following errors

`make[1]: Entering directory '/home/pmelnikov/odp/odp/openfastpath/ofp/scripts'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/pmelnikov/odp/odp/openfastpath/ofp/scripts'
Making all in src
make[1]: Entering directory '/home/pmelnikov/odp/odp/openfastpath/ofp/src'
  CC       ofp_pkt_processing.lo
In file included from ofp_pkt_processing.c:35:0:
../include/ofpi.h:12:30: fatal error: odp/helper/linux.h: No such file or directory
compilation terminated.
Makefile:646: recipe for target 'ofp_pkt_processing.lo' failed
make[1]: *** [ofp_pkt_processing.lo] Error 1
make[1]: Leaving directory '/home/pmelnikov/odp/odp/openfastpath/ofp/src'
Makefile:587: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
`

I tried to checkout ODP branch origin/monarch_lts, but with no result.
Any help is appreciated. I know i need to edit makefiles manually, but is there any other way to fix this?
Thanks

**Comment by rishdas** [comment]
Try building odp monarch_lts branch with --enable-helper-linux flag during the configure stage.

**Comment by Pavel-Melnikov** [comment]
I have tried with --enable-helper-linux, and now I have cannot find input file: include/odp/api/spec/deprecated.h.in

**Comment by Pavel-Melnikov** [comment]
Also could someone please clarify the variable  --prefix=<INSTALL ODP TO THIS DIR>. Is this a root path where ODP source is or should it be something another?

**Comment by Pavel-Melnikov** [comment]
And also I cannot understand a behaviour of confiure with .in files. Should they be created by myself?

**Comment by bogdanPricope** [comment]
Hi,

Take a look at this: https://git.linaro.org/lng/ofp_ci.git/tree/ofp_fpm_burstmode/server/ofp_fpm_burstmode.yaml

OFP is using ODP at monarch_lts tag... you need to branch there.
„prefix” is autotools install prefix: https://www.gnu.org/software/autoconf/manual/autoconf-2.60/html_node/Installation-Names.html

For ODP:
./configure --prefix=some_folder/odp_install

--prefix – is location of odp bins after „make install”

For OFP:
./configure --with-odp=some_folder/odp_install --prefix=some_folder/OFP_install --with-config-flv=$OFP_CONFIG_FLV

--with-odp – is location of odp bins (same as prev. step)
--prefix – is location of ofp bins after ‚make install’

.in files are generated.

BR,
B.

**Comment by Pavel-Melnikov** [comment]
Thank you, will try

**Comment by Pavel-Melnikov** [comment]
Thank you. I have fixed those issues. But now I'm facing an issue that fp0 cannot be found

**Comment by Pavel-Melnikov** [comment]
Also I have noticed an issue that fp interface after start is not created. It uses my eth iface , i can ping it, it still has the same name, but my DNS stopped to respond.
