### ISSUE TITLE
run example failed

### ISSUE THREAD

**Issue by kheirabadi** [OpenFastPath/ofp#176]
Hi,
I can't run any example. please tell me steps required to run webserver example. I used scripts/devbuild_ofp_odp_dpdk.sh to compile ofp, odp, dpdk.

**Comment by dosarudaniel** [comment]
Hi, @kheirabadi ,

Try these commands before running the webserver: (more info in step 4, [here](https://git.linaro.org/lng/odp-dpdk.git/tree/platform/linux-dpdk/README) )

Reserve hugepages:
```
sudo sh -c 'echo 1024 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages'
```
Mount hugetlbfs:
```
sudo mkdir /mnt/huge
sudo mount -t hugetlbfs nodev /mnt/huge
```
Insert DPDK kernel module:
```
sudo /sbin/modprobe uio
cd <director where you installed ofp>/script/dpdk
sudo insmod x86_64-native-linuxapp-gcc/kmod/igb_uio.ko
```
Bind NIC's to DPDK:
```
./tools/dpdk-devbind.py --status # show your available NICs
sudo ifconfig <NIC name to bind> down # <NIC name to bind> example eth0
sudo ./usertools/dpdk-devbind.py --bind=igb_uio <NIC name to bind>
```
Then run the webserver, from ~/ofp/example/webserver$:
```
sudo ODP_PLATFORM_PARAMS="-n 4" ./webserver -i 0 -c 2
```

**Comment by kheirabadi** [comment]
hi dear,
I follow steps you guide me, but the program can''t execute. the output is:

RLIMIT_CORE: 0/-1
Setting to max: 0
EAL: Detected 16 lcore(s)
EAL: Probing VFIO support...
EAL: Failed to remap 2 MB pages
PANIC in rte_eal_init():
Cannot init memory

Regards,
hamid

On Thu, 08/31/2017 03:43 PM, Daniel-Florin Dosaru <notifications@github.com> wrote:
> 
Hi, @kheirabadi ,
Try these commands before running the webserver: (more info in step 4, here )
Reserve hugepages:
sudo sh -c 'echo 1024 > /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages'

Mount hugetlbfs:
sudo mkdir /mnt/huge
sudo mount -t hugetlbfs nodev /mnt/huge

Insert DPDK kernel module:
sudo /sbin/modprobe uio
cd <director where you installed ofp>/script/dpdk
sudo insmod x86_64-native-linuxapp-gcc/kmod/igb_uio.ko

Bind NIC's to DPDK:
./tools/dpdk-devbind.py --status # show your available NICs
sudo ifconfig <NIC name to bind> down # <NIC name to bind> example eth0
sudo ./usertools/dpdk-devbind.py --bind=igb_uio <NIC name to bind>

Then run the webserver, from ~/ofp/example/webserver$:
sudo ODP_PLATFORM_PARAMS="-n 4" ./webserver -i 0 -c 2

—
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.




  
 *

**Comment by ViktorTikkanen** [comment]
Hi kheirabadi!

Do you still have problems with running ODP-DPDK based OFP applications? If so, can you please try following things:

1. Run the latest version of scripts/devbuild_ofp_odp_dpdk.sh script (pushed 17.10.2017). Among other changes, it installs newer version of DPDK (17.02).

2. Try to remount hugetlbfs:

umount -a -t hugetlbfs
mount -t hugetlbfs nodev /mnt/huge

If this will not help, please sent the output of 'cat /proc/meminfo' command before and after starting an OFP application. You can also try to run DPDK's own test application (testpmd) in order to troubleshoot possible DPDK problems.
