### ISSUE TITLE
Environment - bare metal

### ISSUE THREAD

**Issue by semihalf-berestovskyy-andriy** [OpenFastPath/ofp#19]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 19
Date: 2015-06-03 08:43:18 +0200
From: Bogdan Pricope &lt;<bogdan.pricope@enea.com>&gt;
To:   Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;
CC:   jose.pekkarinen@nokia.com

Last updated: 2015-11-24 11:52:20 +0100

## Bugzilla Comment ID: 24
Date: 2015-06-03 08:43:18 +0200
From: Bogdan Pricope &lt;<bogdan.pricope@enea.com>&gt;

Environment - bare metal

## Bugzilla Comment ID: 130
Date: 2015-11-24 11:36:51 +0100
From: José Pekkarinen &lt;<jose.pekkarinen@nokia.com>&gt;

Can anyone elaborate in what is this all about?

## Bugzilla Comment ID: 136
Date: 2015-11-24 11:52:20 +0100
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

Run OFP in an environment that excludes Linux.
OFP application should run in other OSs and have no dependency to Linux or others.

**Comment by sovu** [comment]
Added 161026-ENEA-13 topic on the roadmap list
