### ISSUE TITLE
RST packets contain TCP options and data

### ISSUE THREAD

**Issue by jvillanyi** [OpenFastPath/ofp#190]
The ofp_tcp_respond() function, among other things, is used for generating TCP RST packets in response to bad incoming packets. Instead of allocating a new mbuf for the RST, the function reuses the mbuf of the incoming packet. Even though the function correctly updates the packet length within the inherited IP header, it fails to do so for the frame length within the ODP header.
Consequently, the ODP buffer of the outgoing RST packet will continue to include any TCP options and/or data inherited from the incoming packet. This can cause various problems for the resulting RST, including bad Ethernet FCS values, bad TCP checksums (in case of TCP checksum hardware offload), etc.

The patch below fixes the problem by truncating the tail of the ODP packet to the correct length:
\---
 src/ofp_tcp_subr.c | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/src/ofp_tcp_subr.c b/src/ofp_tcp_subr.c
index 75affc5..43185ac 100644
--- a/src/ofp_tcp_subr.c
+++ b/src/ofp_tcp_subr.c
@@ -663,6 +663,11 @@ ofp_tcp_respond(struct tcpcb *tp, void *ipgen, struct ofp_tcphdr *th, odp_packet
        if (tp == NULL || (inp->inp_socket->so_options & OFP_SO_DEBUG))
                tcp_trace(TA_OUTPUT, 0, tp, (void *)odp_packet_data(m), th, 0);
 #endif
\+       if (valid_m) {
\+         int pktlen = odp_packet_len(m);
\+         KASSERT(pktlen >= tlen, ("pktlen %d too small", pktlen));
\+         odp_packet_trunc_tail(&m, pktlen - tlen, NULL, NULL);
\+       }
 #ifdef INET6
        if (isipv6)
                (void) ofp_ip6_output(m, NULL);
\---
I have submitted this patch to the OFP mailing list as well.

**Comment by sovu** [comment]
Pushed on 8 december 2017 with commit: 8caa89
