### ISSUE TITLE
Are functions like packet filtering firewall implemented in  ofp?

### ISSUE THREAD

**Issue by WenqingWu** [OpenFastPath/ofp#199]

**Comment by sovu** [comment]
Hi,

I think you are referring to access control list (ACL) type functionality. This type of functionality is not implement at this moment.

This is a feature that we would like to implement and we have it on our whishlist / uncommited roadmap.

We will be glad to receive your contribution after signing a CLA:
https://openfastpath.org/wp-content/uploads/2018/01/OpenFastPath_ContributionAgreement.pdf

Kind Regards,
Sorin
