### ISSUE TITLE
make compile error with latest version of odp 

### ISSUE THREAD

**Issue by jestan** [OpenFastPath/ofp#2]
I am trying to build ofp and getting following compilation error.

It looks like pthread_create function has been changed in odp.

commit 1a7893cf034dcb0045c3f7a08559b0955b3093b5
Date:   Wed Dec 16 15:14:14 2015 +0530

helper: linux: add thread type in pthread_create
    
The exisiting helper routine only create the worker threads.
However there is a need to use the same for creating the control
thread as well. e.g. CLI thread.

```
build@ubuntu:~/sources/ofp$ make
Making all in src
make[1]: Entering directory `/home/build/sources/ofp/src'
  CC       ofp_avl.lo
  CC       cli/ofp_cli.lo
cli/ofp_cli.c: In function 'ofp_start_cli_thread':
cli/ofp_cli.c:1724:6: error: too few arguments to function 'odph_linux_pthread_create'
  if (odph_linux_pthread_create(&ofp_global_cfg->cli_thread,
      ^
In file included from cli/ofp_cli.c:24:0:
/home/build/installs/odp/include/odp/helper/linux.h:67:5: note: declared here
 int odph_linux_pthread_create(odph_linux_pthread_t *thread_tbl,
     ^
make[1]: *** [cli/ofp_cli.lo] Error 1
make[1]: Leaving directory `/home/build/sources/ofp/src'
make: *** [all-recursive] Error 1
```

**Comment by bogdanPricope** [comment]
Latest supported ODP version is 1.4.0
Adding support for ODP 1.5.0 and 1.6.0 is in progress.

**Comment by jestan** [comment]
Build environment preparation section in the readme doesn't mention about required ODP version.

**Comment by bogdanPricope** [comment]
FAQ section:
" 
Q: What versions of ODP does OFP support?

A: At the moment it supports all the way from 1.1.0 to 1.4.0"

ODP 1.5.0 patches are in.

**Comment by jestan** [comment]
Build sections says,

Download ODP:
	git clone git://git.linaro.org/lng/odp.git

When I tried it , I got the latest version which was not supported.
It will be better if you can say, clone the ODP tag 1.4.0, not the master.

Just my few cents.

**Comment by semihalf-berestovskyy-andriy** [comment]
Note: the comment was created automatically with bugzilla2github tool

---
**Bugzilla bug ID:  2**
**Renumbered to issue: #125**
