### ISSUE TITLE
Segmentation fault in  default_event_dispatcher 

### ISSUE THREAD

**Issue by RadulescuValentin** [OpenFastPath/ofp#203]
This is escalated from https://github.com/Linaro/odp/issues/592

Below the backtrace: 

Thread 3 "webserver" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffaa5ff700 (LWP 1964)]
0x000000000040a6ee in default_event_dispatcher (arg=0x40a370 <ofp_eth_vlan_processing>) at ofp_pkt_processing.c:73
73 int rx_burst = global_param->evt_rx_burst_size;
(gdb) bt
#0 0x000000000040a6ee in default_event_dispatcher (arg=0x40a370 <ofp_eth_vlan_processing>) at ofp_pkt_processing.c:73
#1 0x00007ffff7bd32f7 in _odph_thread_run_start_routine (arg=0x7fffffffd4d0) at threads.c:56
#2 0x00007ffff6fa36ba in start_thread (arg=0x7fffaa5ff700) at pthread_create.c:333
#3 0x00007ffff6cd941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) print global_param
$1 = (ofp_global_param_t *) 0x0

**Comment by RadulescuValentin** [comment]
Hi Jere,

Can you please take a look at this crash?

**Comment by JereLeppanen** [comment]
@RadulescuValentin Will do. I've assigned this to myself.
