### ISSUE TITLE
OFP update vs. odp?

### ISSUE THREAD

**Issue by bogdanPricope** [OpenFastPath/ofp#233]
Any plan to update OFP to support odp 1.23?

**Comment by psavol** [comment]
Did you have a specific problem with the latest ODP?

I just built OFP with latest ODP master. ODP configure needs to include --enable-deprecated. However, OFP does not link correctly when ODP uses DPDK. We'll fix that shortly.

**Comment by bogdanPricope** [comment]
As far as I know, v1.23.0.0_DPDK_18.11 and v1.23.0.0 are the latest tags on odp-dpdk/odp repos.
It makes sense (for OFP) to switch to latest ODP (odp-dpdk) 'release' version.

I am running ofp with odp-dpdk .. I am not aware of the issues from the main repo(sorry).

**Comment by bogdanPricope** [comment]
I mean, OK, we can build ODP with '--enable-deprecated' and add Matias's PR to fix the linking issues with 'ipv4_fwd' (and it builds) but will not be more appropriate (from OFP point of view) to actually update the ofp code to work with latest version (tag) of ODP? 
The changes are trivial as far as I understand (https://github.com/bogdanPricope/ofp/commit/b46a71403ffca2cdd6b93e9882cec510718b7ac6). 

By the way, I am contributing as 'independent contributor' and I am no longer with Enea. So, those are only my opinions.

**Comment by matiaselo** [comment]
Hi Bogdan,

As you said the required changes to support the latest ODP version seem to be quite trivial. I already have a "working" but untested branch in my local private repo. Hopefully I'll have enough time next week to finish the patch set.

**Comment by bogdanPricope** [comment]
Nice. Thank you, Matias.

Have a nice weekend.

**Comment by matiaselo** [comment]
@bogdanPricope I've now posted a PR (#236) to enable OFP usage with the latest ODP code. Comments are appreciated if you have time.

**Comment by bogdanPricope** [comment]
Hi Matias, I'll have a look in the following hours. 
Best regards,

**Comment by matiaselo** [comment]
> Hi Matias, I'll have a look in the following hours.
> Best regards,

Thanks!
