### ISSUE TITLE
Potential odp_packet_t double free

### ISSUE THREAD

**Issue by QinLongFei** [OpenFastPath/ofp#265]
In ofp_packet_input, if pkt_func return OFP_PKT_DROP, this packet will be freed. But after that, it will be freed again in ofp_sp_input if SP is not defined.

![image](https://user-images.githubusercontent.com/14818295/111865088-eafa2700-899f-11eb-85b2-2b4a01c9d6f3.png)

**Comment by bogdanPricope** [comment]
If res is OFP_PKT_DROP then  is not OFP_PKT_CONTINUE. So return will be called.
 
	if (res != OFP_PKT_CONTINUE)
		return res;

**Comment by QinLongFei** [comment]
You are right! Thanks
