### ISSUE TITLE
This project has been fallen behind odp too long.

### ISSUE THREAD

**Issue by ybbh** [OpenFastPath/ofp#274]
My build environment is Ubuntu22.04 LTS with GCC 11.2.0.
When I built this project with the latest odp code GCC complained error:
`../include/ofpi_init.h:24:9: error: unknown type name 'odph_odpthread_t'`

In odp project, odph_odpthread_t was marked as deprecated.

**Comment by bogdanPricope** [comment]
Hi ybbh,

Without an active maintainer on this repository there are not many options.

You can try to build odp (or odp-dpdk) with --enable-deprecated option:
e.g.
./configure ...  --enable-deprecated

OR

You can try to use nfp repository https://github.com/NetInoSoftware/nfp that uses odp-dpdk v1.31.0.1 and DPDK v19.11.
Note: This is a 'demo' repository with the ofp library provided as binary.

Best regards,
Bogdan

**Comment by JereLeppanen** [comment]
Updated to ODP API v1.35.0.0 in #278.
