### ISSUE TITLE
odp classifier sample app issue

### ISSUE THREAD

**Issue by savitakulk** [OpenFastPath/ofp#283]
We are trying to run odp_classifier sample application on VMs with the Mellanox platform and getting the following errors. Any suggestions would be helpful.
--------------------------------------------------------------
ODP:27.12.2022(13:56:23):[ERROR]:[../linux-generic/odp_packet_io.c:594]:odp_pktio_start():DBG: Inside odp_pktio_start
ODP:27.12.2022(13:56:23):[ERROR]:[../linux-generic/odp_packet_io.c:599]:odp_pktio_start():DBG: calling get_pktio_entry
ODP:27.12.2022(13:56:23):[ERROR]:[../linux-generic/odp_packet_io.c:605]:odp_pktio_start():DBG: calling lock_entry
ODP:27.12.2022(13:56:23):[ERROR]:[../linux-generic/odp_packet_io.c:614]:odp_pktio_start():DBG:calling entry->s.ops->start
mlx5_pci: port 0 empty mbuf pool
mlx5_pci: port 0 Rx queue allocation failed: Cannot allocate memory
ODP:27.12.2022(13:56:23):[ERROR]:[odp_packet_dpdk.c:1725]:dpdk_start():Device start failed: err=-12, port=0
ODP:27.12.2022(13:56:23):[ERROR]:[../linux-generic/odp_packet_io.c:623]:odp_pktio_start():DBG: res of entry->s.ops->start -1
ODP:27.12.2022(13:56:23):[ERROR]:[../linux-generic/odp_packet_io.c:625]:odp_pktio_start():DBG:calling ODP_PKTIN_MODE_SCHED
ODP:27.12.2022(13:56:23):[ERROR]:[../linux-generic/odp_packet_io.c:626]:odp_pktio_start():DBG:calling ODP_PKTIN_MODE_SCHED 1 mode 1
ODP:27.12.2022(13:56:23):[ERROR]:[../linux-generic/odp_packet_io.c:633]:odp_pktio_start():DBG:num = 1
ODP:27.12.2022(13:56:23):[ERROR]:[../linux-generic/odp_packet_io.c:644]:odp_pktio_start():DBG:calling odp_sched_fn->pktio_start
ODP:27.12.2022(13:56:23):[DEBUG]:[../linux-generic/odp_packet_io.c:650]:odp_pktio_start():interface: 0, input queues: 1, output queues: 1
odp_classifier.c:711:main():Error: unable to start pktio
---------------------------------------------------------------

P.S: We are running the classifier with the following command

./odp_classifier -i 1 -m 0 -p "ODP_PMR_SIP_ADDR:10.10.10.0:0xFFFFFF00:queue1" -p "ODP_PMR_SIP_ADDR:10.10.10.10:0xFFFFFFFF:queue1:queue2"

**Comment by MatiasElo** [comment]
Hi @savitakulk,

Looks like this issue belongs to [ODP project](https://github.com/OpenDataPlane/odp/issues). When you recreate the issue there, please list used SW versions (ODP, DPDK) and pktio type (normal or zero-copy).

**Comment by savitakulk** [comment]
> zero-copy



> Hi @savitakulk,
> 
> Looks like this issue belongs to [ODP project](https://github.com/OpenDataPlane/odp/issues). When you recreate the issue there, please list used SW versions (ODP, DPDK) and pktio type (normal or zero-copy).

Thanks a lot for the input. We are using DPDK version-dpdk-20.11.1 ,odp version as -release 2.9.1 and pktio type as normal.I will recreate the issue at https://github.com/OpenDataPlane/odp/issues mentioning all this.

**Comment by savitakulk** [comment]
> However, if a network stack is what you need, you may try OFP classifier example or NFP project.

Thanks a lot for your suggestions/inputs.Currently we are trying with ODP classifier.
