### ISSUE TITLE
Compile fail on v1.0 when --enable-sp=no

### ISSUE THREAD

**Issue by microelec** [OpenFastPath/ofp#3]
Miss a 'SP' macro in ofp_init_pre_global function. Not sure master has same issue. :)
Error log like this.
ofp_init.c: In function 'ofp_init_pre_global':
ofp_init.c:116:5: error: 'struct ofp_global_config_mem' has no member named 'nl_thread_is_running'
  shm->nl_thread_is_running = 0;

**Comment by bogdanPricope** [comment]
This issue was fixed on:
commit aa858aba7200c7f7bd34414841e1d89f1f266030
Author: Bogdan Pricope <bogdan.pricope@enea.com>
Date:   Wed Dec 9 10:41:28 2015 +0200

    Fix error obtained when building OFP without slowpath support

    Signed-off-by: Bogdan Pricope <Bogdan.Pricope@enea.com>
    Reviewed-and-tested-by: JosĂŠ Pekkarinen <jose.pekkarinen@nokia.com>

**Comment by semihalf-berestovskyy-andriy** [comment]
Note: the comment was created automatically with bugzilla2github tool

---
**Bugzilla bug ID:  3**
**Renumbered to issue: #126**
