### ISSUE TITLE
Identify configuration points as defines/variables/parameters (with review)

### ISSUE THREAD

**Issue by semihalf-berestovskyy-andriy** [OpenFastPath/ofp#49]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 49
Date: 2015-10-21 10:06:00 +0200
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;
To:   Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;
CC:   ciprian.barbu@enea.com

Last updated: 2015-11-26 12:20:03 +0100

## Bugzilla Comment ID: 61
Date: 2015-10-21 10:06:00 +0200
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

Ex: like the one that change the memory consumption inside the route table.

Create a new issue for each situation identified by review.

## Bugzilla Comment ID: 68
Date: 2015-10-21 12:00:43 +0200
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

- hard-coded values such as number of ports (GRE port) and ARP timeout should be configurable.

## Bugzilla Comment ID: 89
Date: 2015-11-02 14:35:48 +0100
From: Ciprian Barbu &lt;<ciprian.barbu@enea.com>&gt;

ofp_arp.c:411 - ofp_arp_save_ipv4_pkt computes newarp using hardcoded value of 5; although this is inside a sanity check block I think the value should at least be explained in a comment above.

## Bugzilla Comment ID: 145
Date: 2015-11-26 12:20:03 +0100
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

Changes were made. We can close this.

**Comment by sovu** [comment]
To be closed when roadmap item 161019-MH-2 is resolved.

"OFP aplication compile time flags migrate to run time config options, or core OFP fixes for performance
In an NFV enviroment the out of the box should work, with tuning (run time config it may run beter for your app) But you cannot have OFP built for every application."
