### ISSUE TITLE
Create a configurable model for Sync/Lock primitives.

### ISSUE THREAD

**Issue by semihalf-berestovskyy-andriy** [OpenFastPath/ofp#50]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 50
Date: 2015-10-21 10:08:26 +0200
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;
To:   Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

Last updated: 2015-10-21 10:08:26 +0200

## Bugzilla Comment ID: 62
Date: 2015-10-21 10:08:26 +0200
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

Sync/Lock primitives can be disabled in some scenarios.

**Comment by brbrooks** [comment]
Is this still valid?  What are the scenarios?

**Comment by sovu** [comment]
There was a discussion a while ago in the TSC and we want generic implementation and not customize lib on the usecase.
