### ISSUE TITLE
OFP automatic test framework

### ISSUE THREAD

**Issue by semihalf-berestovskyy-andriy** [OpenFastPath/ofp#65]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 65
Date: 2015-10-22 17:10:10 +0200
From: Rasmuss &lt;<rasmuss.graaf@enea.com>&gt;
To:   Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

Last updated: 2015-11-13 12:23:21 +0100

## Bugzilla Comment ID: 84
Date: 2015-10-22 17:10:10 +0200
From: Rasmuss &lt;<rasmuss.graaf@enea.com>&gt;

Ericsson reported that ofp_init_global had compatibility issues with ODP 1.3, should a ODP version check be added to OFP?

How do we test various configurations? (what's the test scope/matrix?)

## Bugzilla Comment ID: 103
Date: 2015-11-13 12:19:17 +0100
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

Added support for ODP v1.4 and older versions. Older versions should be supported as build option.

All tests are applied as ODP case for latest OFP master and latest ODP version. I believe we don't intend to test all ODP versions, but only the last one, over latest master of OFP.

We should have an automatic test environment. All cunit tests should PASS with each added patch. This is done manually.

**Comment by sovu** [comment]
I agree with Viktor!
