### ISSUE TITLE
OFP .configure error

### ISSUE THREAD

**Issue by Chadster766** [OpenFastPath/ofp#7]
I've run the successfully below command to make ODP:
```
./bootstrap
./configure --prefix=/usr/local/odp
make
make install
```

The build configuration fails for OFP with the below commands:
```
./bootstrap
./configure --prefix=/usr/local/ofp --with-odp=/usr/local/odp --enable-cunit
```

Error displayed:
```
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ODP... no
checking for ODP... no
checking for ODP... no
checking for ODP... no
checking for ODP... no
checking for ODP... no
checking for ODP... no
checking for ODP... no
checking for odp_packet_alloc in -lodp... no
configure: error: "This package needs OpenDataPlane (libodp.a) installed"
```

**Comment by bogdanPricope** [comment]
Hi,

First to check is the ODP version. OFP supports ODP up to v1.7.0.0

Best regards,
Bogdan

**Comment by Chadster766** [comment]
I made sure ODP was build from GIT tag "v1.7.0.0".

Still the same error.

**Comment by Chadster766** [comment]
Does it make a difference if it's built in a chroot?

**Comment by Chadster766** [comment]
The solution was to build against ODP version 1.3.0

**Comment by semihalf-berestovskyy-andriy** [comment]
Note: the comment was created automatically with bugzilla2github tool

---
**Bugzilla bug ID:  7**
**Renumbered to issue: #130**
