### ISSUE TITLE
Ping sent from Linux is not working

### ISSUE THREAD

**Issue by semihalf-berestovskyy-andriy** [OpenFastPath/ofp#74]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 74
Date: 2016-01-14 09:47:36 +0100
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;
To:   Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

Last updated: 2016-01-14 14:23:16 +0100

## Bugzilla Comment ID: 147
Date: 2016-01-14 09:47:36 +0100
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

The ICMP Reply is captured by OFP. We should fallback the ICMP Replies to Slow path.

The solution might be a oneline change on the return value of ICMP reply processing function.

## Bugzilla Comment ID: 148
Date: 2016-01-14 14:23:16 +0100
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

David Nystrom: there seems to be some ARP table bouncing if a ping over TAP interface is attempted. It also makes a laptop usable as a test environment without loosing local network connectivity :)

**Comment by iufl** [comment]
The issue isn't reproducible any more.
