### ISSUE TITLE
Pointers in shared memory work only in some environments

### ISSUE THREAD

**Issue by semihalf-berestovskyy-andriy** [OpenFastPath/ofp#76]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 76
Date: 2016-02-08 11:08:37 +0100
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;
To:   Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

Last updated: 2016-03-04 10:45:55 +0100

## Bugzilla Comment ID: 150
Date: 2016-02-08 11:08:37 +0100
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

free_* pointers and pointers in ofp_rtl_node structure should be avoided.

A SHM will have different pointer values on each context.

Now it seems this works because threads have access to the same addresses.

## Bugzilla Comment ID: 156
Date: 2016-03-04 10:45:55 +0100
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

The shm pointers should be equall on all threads/processes.
On linux environment this happens, but this might be true for all environments.

In this case the redesign work to replace pointers with some indexes in shm would be masive.

**Comment by JannePeltonen** [comment]
This is fixed by cc24ec6c208396ee43396ee456cda4cc9a162685 which uses the new ODP_SHM_SINGLE_VA flag to request SHM blocks to have the same address mapping in all threads. The fix requires new enough ODP (>= 1.13.0.0) that has the flag and makes OFP depend on the availability of such a mapping.
