### ISSUE TITLE
Parameters from ofp_config.h should be configurable.

### ISSUE THREAD

**Issue by semihalf-berestovskyy-andriy** [OpenFastPath/ofp#79]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 79
Date: 2016-03-04 10:31:56 +0100
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;
To:   Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

Last updated: 2016-03-04 10:31:56 +0100

## Bugzilla Comment ID: 153
Date: 2016-03-04 10:31:56 +0100
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

Need to find a way on how to init these from application or to have more predefined patterns activated from configure script.

For example, in the TCP webserver usecase one needs to have a patch over OFP:
 /** Packet pool size. */
-#define SHM_PKT_POOL_SIZE              (512*2048)
+#define SHM_PKT_POOL_SIZE              (512*2048*8*2)
 
 /**Maximum number of sockets. */
-#define OFP_NUM_SOCKETS_MAX 1024
+#define OFP_NUM_SOCKETS_MAX 60000

**Comment by sovu** [comment]
#79 Parameters from ofp_config.h should be configurable. 
-->
commit c1616bcec86eef7ce57ed92f4ad09ce7c4f39f00
Author: Bogdan Pricope <bogdan.pricope@enea.com>
Date:   Mon Oct 24 17:22:36 2016 +0300

    Add configure.ac option for setting OFP configuration flavor

    Signed-off-by: Bogdan Pricope <bogdan.pricope@linaro.org>
    Reviewed-by: Sorin Vultureanu <sorin.vultureanu@enea.com>
