### ISSUE TITLE
Can't build User Guides

### ISSUE THREAD

**Issue by Chadster766** [OpenFastPath/ofp#8]
The README say that ".configure --enable-user-guide" should work.

configure: WARNING: unrecognized options: --enable-user-guide

**Comment by Chadster766** [comment]
This make option works with version v1.4.0.0 with graphviz package installed.

**Comment by Chadster766** [comment]
On v1.3.0 asciidoc package needs to be installed

**Comment by Chadster766** [comment]
Sorry this was posted in the wrong GitHub repo. This was concerning Open Data Plane.

**Comment by semihalf-berestovskyy-andriy** [comment]
Note: the comment was created automatically with bugzilla2github tool

---
**Bugzilla bug ID:  8**
**Renumbered to issue: #131**
