### ISSUE TITLE
ofp_config.h: replace with more flexible approach

### ISSUE THREAD

**Issue by semihalf-berestovskyy-andriy** [OpenFastPath/ofp#89]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 89
Date: 2016-07-05 07:30:16 +0200
From: Ivan Koveshnikov &lt;<ikoveshnik@gmail.com>&gt;
To:   Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

Last updated: 2016-07-05 07:30:16 +0200

## Bugzilla Comment ID: 172
Date: 2016-07-05 07:30:16 +0200
From: Ivan Koveshnikov &lt;<ikoveshnik@gmail.com>&gt;

OFP has 3 different configuration sets: default, webserver, netwrap-webserver; and some options are contolled by configure.ac, such as INET, INET6, SP

All the configurations should be in the same location. The best way to organize them up is to use menuconfig-like approach, this can help storing a bunch of configuration options, dependencies.

Current configuration sets can be implemented as defconfig samples.

**Comment by sovu** [comment]
Now some options depending on the usecase and build time are controlled through configure.ac.
We have a framework to support runtime configuration parameters from code or a parameter configuration file.
All important parameters were moved from ofp_config.h file to runtime configuration framework.

**Comment by sovu** [comment]
commit c1616bcec86eef7ce57ed92f4ad09ce7c4f39f00 (Add configure.ac option for setting OFP configuration flavor)
partly duplicate for the open #49 (Identify configuration points as defines/variables/parameters (with review)).

-Viktor
