### ISSUE TITLE
TCP speed limitation with big file transfer

### ISSUE THREAD

**Issue by semihalf-berestovskyy-andriy** [OpenFastPath/ofp#99]
Note: the issue was created automatically with bugzilla2github tool

# Bugzilla Bug ID: 99
Date: 2016-10-05 11:11:55 +0200
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;
To:   Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

Last updated: 2016-11-22 15:37:40 +0100

## Bugzilla Comment ID: 186
Date: 2016-10-05 11:11:55 +0200
From: Sorin Vultureanu &lt;<sorin.vultureanu@enea.com>&gt;

The webserver performance is limited by this, intermittently I am able to get 260MB/s of traffic using one core, other times it reduces speed because of the filling of so->so_snd and synchronisation needed.

**Comment by JereLeppanen** [comment]
I think this should be fixed now, can you confirm @sovu ?

**Comment by sovu** [comment]
wget 192.168.1.4:2048/file.txt
--2017-04-10 13:01:05--  http://192.168.1.4:2048/file.txt
Connecting to 192.168.1.4:2048... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/plain]
Saving to: 'file.txt.16'

file.txt.16             [  <=>               ] 100.00M   381MB/s    in 0.3s    

2017-04-10 13:01:06 (381 MB/s) - 'file.txt.16' saved [104857600]
